---
- name: Setup couple variables
  set_fact:
    public_ip: "{{ ansible_host }}"
    private_ip: "{{ hostvars[ansible_host].private_ip }}"
    node_name: "{{ hostvars[ansible_host].inter_name }}"
    fabricroot: "/opt/fabric"

- name: Upload addon service configuration files
  template:
    src: "{{ playbook_dir }}/../env_k8s/post/templates/{{ item }}.j2"
    dest: "/etc/kubernetes/{{ item }}.yaml"
    mode: 0644
  with_items:
    - dnscontroller
    - dashboard

- name: Label the master node
  command: >-
    {{ fabricroot }}/bin/kubectl --server={{ private_ip }}:8080 label --overwrite=true
    nodes {{ node_name }} dashboardId=master

- name: Create addon services
  command: >-
    {{ fabricroot }}/bin/kubectl --server={{ private_ip }}:8080 create
    -f /etc/kubernetes/{{ item }}.yaml
  with_items:
    - dnscontroller
    - dashboard