---
- name: Ensure dashboard deploy yaml file is removed
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/kubernetes/dashboard.yaml"
    - "/etc/kubernetes/dnscontroller.yaml"