---
- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"

- name: build fabric artifacts
  hosts: builders
  gather_facts: true
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/fabricbuild/tasks/main.yml"
  roles:
    - fabricbuild
  tags: "fabricbuild"
 
- name: generate certificates
  hosts: builders
  gather_facts: false
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/certsetup/tasks/{{ mode }}.yml"
  roles:
    - certsetup
  tags: "certsetup" 

- name: setup fabric network
  hosts: allnodes
  gather_facts: false
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/fabricsetup/tasks/{{ mode }}.yml"
  roles:
    - fabricsetup
  tags: "fabricsetup" 

- name: inform the installer
  hosts: cloud
  connection: local
  tasks:
    - debug:
        msg: >-
          The work load started at {{ hostvars.cloud.starttime.time }},
          ended at {{ ansible_date_time.time }}