---
- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"
  tags: "info"

- name: Prepare to run the workload
  hosts: cloud
  connection: local
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/prepare/tasks/{{ action }}.yml"
  roles:
    - prepare
  tags: "prepare"

- name: provision servers
  hosts: prohosts
  connection: local
  strategy: free
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/provision/tasks/{{ action }}.yml"
  roles:
    - provision
  tags: "provision"

- name: Post provision process
  hosts: cloud
  connection: local
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/postprovision/tasks/{{ action }}.yml"
  roles:
    - postprovision
  tags: "postprovision"

- name: initialize all the servers
  hosts: allnodes
  strategy: free
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/nodeinit/tasks/{{ action }}.yml"
  roles:
    - nodeinit
  tags: "nodeinit"

- name: Inform the installer
  hosts: cloud
  connection: local
  tasks:
    - debug:
        msg: >-
          The work load started at {{ hostvars.cloud.starttime.time }},
          ended at {{ ansible_date_time.time }}
  tags: "info"