---
- name: Figuring out the server architecture
  shell: uname -m | sed 's|i686|386|' | sed 's|x86_64|amd64|'
  register: rawarch

- name: Setup variables
  set_fact:
    goroot: "/opt/go"
    gopath: "/opt/gopath"
    fabricpath: "/opt/gopath/src/github.com/hyperledger/fabric"
    arch: "{{ rawarch.stdout}}"

- name: Setup hyperledger directory
  file:
    path: "{{ fabricpath }}"
    state: directory
    mode: 0775

- name: Pull hyperledger fabric base image
  command: docker pull hyperledger/fabric-baseimage:"{{ fabric.baseimage_tag }}"
  tags: "baseimage"

- name: Extract hyperledger fabric code
  git: 
    repo: "{{ GIT_URL | default('http://gerrit.hyperledger.org/r/fabric') }}"
    dest: "{{ fabricpath }}"
    force: yes
    refspec: "{{ GERRIT_REFSPEC | default('') }}"
    version: "{{ (GERRIT_REFSPEC == '') | ternary('FETCH_HEAD','HEAD') }}"
    depth: 1
  tags: "code"

- name: Make targets
  command: make "{{ target | default('native') }}"
  args:
    chdir: "{{ fabricpath }}"
  register: result
  environment:
    GOROOT: "{{ goroot }}"
    GOPATH: "{{ gopath }}"
    PATH: "{{ ansible_env.PATH}}:{{ goroot }}/bin"
  tags: "make"

- name: Display the output of the build
  debug:
    msg: "{{ result.stdout_lines }}"
  when: result is defined