---
#TODO - Instead, test to see if you can delete the VMs as a group based the group tag, 
#since its asking for instance_ids whcih we will have to persist in the apply play

- name: Destroy the AWS EC2 VM
  ec2:
    region: "{{ cluster.region_name }}"
    aws_access_key: "{{ auth.username | default(lookup('env', 'AWS_ACCESS_KEY')) }}"
    aws_secret_key: "{{ auth.password | default(lookup('env', 'AWS_SECRET_KEY')) }}"
    key_name: "{{ cluster.ssh_key_name }}"
    #zone: "{{ zone }}"
    validate_certs: "{{ cluster.validate_certs }}"
    group: "{{ cluster.security_group }}"
    image: "{{ cluster.image_id }}"
    instance_type: "{{ cluster.flavor_name }}"
    state: absent
    wait_timeout: 200
    instance_tags:
      Name: "{{ inventory_hostname }}"
    wait: true
  register: awsvm_state
